# Generated by Django 5.0.2 on 2024-02-24 12:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("polls", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
